### PR TITLE
added "light the torch rule in example"

### PR DESCRIPTION
**Pull request by digitalsatori**
learning elm now and find a great project. I added the mentioned rule to make the lighter a bit useful in the example.

BTW. Do you think adding `UnLink String` in type `ChangeEntity`  is useful? In my added rule, if we have `unlink`, we can simply unlink the location link for both 'lighter' and 'torch' instead of adding the extra 'consumed' tag.

### CODE REVIEW

**Review by jschomay — CHANGES_REQUESTED** [review]
Hi @digitalsatori, thanks for your interest in the Elm Narrative Engine, and thanks for adding this rule!  It is a perfect example of adding a little more puzzle mechanics.

I have a suggested change in your implementation though:

- instead of adding another entity representing a different state of an existing entity (burning vs unburning tourches), just create a single "torch", and start it off with an illumination level of 0.
- using the lighter when the torch is in inventory and has an illumination level of 0, would change the illumination level of the torch.
- you probably want to add a rule when clicking on the torch when the illumination level is 0 to add some custom dialog like, "A perfectly useful torch, except for the fact that is unlit."

This way, you are changing a property on an entity, instead of "swapping" similar entities.  You could do something similar to make the torch "blow out" for example.

As for the lighter, instead of using a tag of "consume", I would either decide that the lighter can be used repeatedly, or I would add a "fuel" stat and decrement it each use, and check against the fuel level on each use.

I have considered an "unlink" change, but decided against it.  Relationships may change over time, but they rarely disappear.  You can always do something like change the location of an item to "offscreen" (or any other random word that doesn't match any entity ids) if you really want to remove it from the game.

If you make the suggested changes and are happy with them, I'll merge this PR. Thanks again!

**Comment by digitalsatori** [comment]
Wow, that's thoughtful. Thank you very much for the detailed instructions. I've made the change accordingly. 
I'm not sure it will be a good idea to add the support for wrapping the update function from client code for the client defined properties though. for example, when player light the torch, I would like to change the name and description of the torch accordingly. or, if I defined an image property for the torch, I would like to change it to burning torch image when the 'light the torch' rule triggered.

**Review by jschomay — APPROVED** [review]

**Comment by jschomay** [comment]
Thanks @digitalsatori, I will merge this.  This will make the example better, so I appreciate your addition!

Regarding changing the name (or description, or image, etc) based on rules - that is a good question, and a point that I think others may have questions around too.  I have purposefully made the engine only responsible for entity id, tags, stats, and links, and let the client handle any other fields.  This is designed for greater flexibility, and a proper separation of concerns, via the Entity Component System design pattern.

In other words, the "Narrative component" handles the entity state, and the client-provided "Display component" handles how to render the entity.  If you want to change the name/description based on a property of an entity, you would use the `assert` api to check if the torch has illumination, and display the name appropriately.

I realize that would be cumbersome, so I have plans on adding a "plugin" for the client to use that adds special parsing of text based on entity state.  For example, the name field could be defined something like this: `"{TORCH.illumination>0 : Burning | Unlit } torch"`.  I've taken this syntax pretty directly from [Inklewriter](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#conditional-text).  This could also allow for various types of repeating text, and could be used in names/descriptions and narrative text, so it should be pretty powerful.  I haven't done this yet, but that is my plan.  Also, since this would be part of the client, and not part of the engine, developers could implement their own solutions any way they please.

**Comment by digitalsatori** [comment]
Thanks @jschomay for accepting my PR. Excited to be a contributor for this project. 
I kind of understand you are purposely limiting the control logic from client side, so that people without coding skill can write play scripts and declarative rules easily (may be with some nice UI interface). In this sense,  the "plugin" is really a nice approach.

Another question here, did you consider the signature of `Links` to be:
```
type alias Links =
    Dict String (Set ID)
```

I think entities may have multiple relationships for certain property, for example `neighbors`, `acquired knowledge`

Sorry for asking question here. Please do let me know if you have better place for discussion.

**Pull request merged**
