### PR TITLE
Push state management outside of the Engine

### PR DESCRIPTION
**Pull request by kofigumbs**
This is the approach that Evan took in his latest architecture demonstrations. I actually ended up killing half the code I touched by getting rid of those intermediate data structures. And now it's typesafe, so you don't have to worry about the error handling!

I'm able to build/play the game as normal. I'm curious to hear your thoughts.

### CODE REVIEW

**Comment by jschomay** [comment]
This is good.  I've realized that both my story descriptions and the story rules are static config and don't need to be loaded as state.  On that note, I would change what you did from being added to the model and just give directly into the upload function through config somehow (it's a bit different as a framework, I'm not sure how to do that yet.)

**Comment by kofigumbs** [comment]
Thanks for taking a look Jeff! I guess I don't know a ton about the use cases you envision, but are you sure the story rules / descriptions will always be static config? The descriptions especially right. It seems plausible that clients would want to provide those dynamically..

**Comment by kofigumbs** [comment]
Also, from an API design perspective, anywhere we depend on a `Dict a b`, we can invert the control flow by relying on a client-provided `a -> b`. I'm thinking about this library as a way to build HTML-representable stories out of arbitrary data structures, so by offloading the inherent story state, we can build a safer library that avoids taking on these tangential concerns.

This was a fun challenge to think about. I noticed you changed your API a bit, so I'm going to close this PR. Feel free to take whatever from here!

**Comment by jschomay** [comment]
Good points for consideration.  My goal is quite specific - I want to build a framework for telling a certain kind of interactive story based on some principles I feel  are worthwhile, rather than make a more flexible library.  I am limiting the client's control purposefully, ideally giving them a context in which to encode a story world and rules to progress through that world.  I want the client code to be more like writing a declarative screenplay rather than coding logic.  In that sense, they are mostly providing a manifest for the engine to play out.

That said, I want to give enough of an api for building compelling, interactive, and dynamic stories.  Finding that balance is the main key challenge of the design.  My plan currently is to allow them to build up a static world (the description info) and some declarative rules which would be matched against given specified interactions and conditions to change the state of the world, and also supply alternative narrative than the static descriptions for such interactions.  I believe this can be accomplished with a the client's code going into config without diminishing the range of interactions they can perform.

Please continue share your thoughts, as it is helpful to talk it through :)

I did merge your commit in after resolving the conflicts by the way.

**Comment by kofigumbs** [comment]
Glad to be a contributor 😄 

I think I understand where you're coming from, but it'll certainly help when we get to sit down next week. I was thinking about the interface more from a data-ownership perspective, but I'd bet there's a way to marry the two ideas: not duplicating the client's data structure and exercising control over their input. Looking forward to thinking about it more!

**Pull request closed without merging**
